apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  creationTimestamp: null
  name: weaveworks-charts
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://weaveworks.github.io/weave-gitops-profile-examples/
status: {}

--- 
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1m
  url: https://github.com/weaveworks/profiles-catalog
  ref:
    branch: main

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
  labels:
    weave.works/applied-layer: layer-0
spec:
  dependsOn:
  - name: external-secrets
    namespace: external-secrets
  interval: 1m
  chart:
    spec:
      chart: ./charts/external-secrets
      sourceRef:
        kind: GitRepository
        name: external-secrets
        namespace: external-secrets
      valuesFiles:
      - ./charts/external-secrets/values.yaml
      interval: 1m
