apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  annotations:
    metadata.weave.works/dashboard.prometheus: https://prometheus.io/
    templates.weave.works/create-request: '{"head_branch":"wge-create-branch-3yxel","title":"Creates
      resource leaf0","description":"This PR creates a waleed-cluster-template-development
      instance","template_name":"waleed-cluster-template-development","parameter_values":{"CLUSTER_NAME":"leaf0","CONTROL_PLANE_MACHINE_COUNT":"1","KUBERNETES_VERSION":"1.23.3","NAMESPACE":"default","WORKER_MACHINE_COUNT":"1"},"commit_message":"Creates
      waleed-cluster-template-development instance","credentials":{},"values":[{"name":"external-secrets","version":"0.6.1","values":"ZXh0ZXJuYWwtc2VjcmV0czoKICBpbnN0YWxsQ1JEczogdHJ1ZQoKc2VjcmV0c1NvdXJjZToKICBlbmFibGVkOiB0cnVlCiAgdXJsOiBzc2g6Ly9naXRAZ2l0aHViLmNvbS93YWxlZWRoYW1tYW0vd2dlLWRldgogICMgdGFnOiB2MS4wLjAKICBicmFuY2g6IG1haW4KICBwYXRoOiAuL2NsdXN0ZXJzL3NlY3JldHMvbWFuYWdlbWVudC8gICMgQ291bGQgYmUgYSBwYXRoIHRvIHRoZSBzZWNyZXRzIGRpciBvciBhIGt1c3RvbWl6YXRpb24ueWFtbCBmaWxlCiAgc2VjcmV0UmVmOiBteS1wYXQgICMgKE9wdGlvbmFsKTogTmFtZSBvZiB0aGUgSzhzIHNlY3JldCB3aXRoIHByaXZhdGUgcmVwbyBhdXRoIGNyZWRlbnRpYWxzCiAgIyBzb3VyY2VSZWY6ICMgQ291bGQgc3BlY2lmeSBhIG5hbWUgZm9yIGFuIGV4aXN0aW5nIEdpdFNvdXJjZSByZWZlcmVuY2UgaW5zdGVhZCBvZiBjcmVhdGluZyBhIG5ldyBvbmUKICAjICAga2luZDogR2l0UmVwb3NpdG9yeQogICMgICBuYW1lOiBleHRlcm5hbC1zZWNyZXRzCiAgIyAgIG5hbWVzcGFjZTogZXh0ZXJuYWwtc2VjcmV0cwo=","layer":"layer-0","namespace":"external-secrets"}],"template_namespace":"default","template_kind":"CAPITemplate"}'
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
    weave.works/apps: capd
    weave.works/flux: bootstrap
  name: leaf0
  namespace: default
spec:
  capiClusterRef:
    name: leaf0

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cni: calico
    secretmanager: aws
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: leaf0
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: leaf0-control-plane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: leaf0
    namespace: default

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: leaf0
  namespace: default

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: leaf0-control-plane
  namespace: default
spec:
  template:
    spec:
      extraMounts:
      - containerPath: /var/run/docker.sock
        hostPath: /var/run/docker.sock

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: leaf0-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
        - 0.0.0.0
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerMachineTemplate
      name: leaf0-control-plane
      namespace: default
  replicas: 1
  version: 1.23.3

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: leaf0-md-0
  namespace: default
spec:
  template:
    spec: {}

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: leaf0-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cgroup-driver: cgroupfs
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: leaf0-md-0
  namespace: default
spec:
  clusterName: leaf0
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: leaf0-md-0
          namespace: default
      clusterName: leaf0
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: leaf0-md-0
        namespace: default
      version: 1.23.3
