apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  creationTimestamp: null
  name: weaveworks-charts
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  timeout: 1m0s
  url: https://raw.githubusercontent.com/weaveworks/weave-gitops-profile-examples/gh-pages
status: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  labels:
    weave.works/applied-layer: layer-0
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.0.8
  install:
    crds: CreateReplace
  interval: 1m0s
  upgrade:
    crds: CreateReplace
  values:
    cert-manager:
      installCRDs: true
status: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: dex
  namespace: flux-system
spec:
  chart:
    spec:
      chart: dex
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.0.12
  dependsOn:
  - name: ondat
  install:
    crds: CreateReplace
  interval: 1m0s
  upgrade:
    crds: CreateReplace
  values:
    dex:
      config:
        enablePasswordDB: true
        issuer: http://my-issuer-url.com
        storage:
          type: memory
      enabled: true
      ingress:
        enabled: true
        hosts:
        - host: my-issuer-url.com
          paths:
          - path: /
            pathType: ImplementationSpecific
status: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  labels:
    weave.works/applied-layer: layer-0
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.0.3
  install:
    crds: CreateReplace
  interval: 1m0s
  upgrade:
    crds: CreateReplace
  values:
    metallb:
      configInline:
        address-pools:
        - addresses:
          - 172.16.20.251/32
          name: default
          protocol: layer2
      prometheus:
        namespace: ""
        podMonitor:
          enabled: false
        prometheusRule:
          enabled: false
status: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  labels:
    weave.works/applied-layer: layer-1
  name: ondat
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ondat
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.0.2
  dependsOn:
  - name: cert-manager
  - name: metallb
  install:
    crds: CreateReplace
  interval: 1m0s
  upgrade:
    crds: CreateReplace
  values:
    ondat:
      etcd-cluster-operator:
        cluster:
          replicas: 3
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
          storage: 6Gi
          storageclass: local-path
      ondat-operator:
        cluster:
          portalManager:
            apiUrl: https://portal-setup-7dy4neexbq-ew.a.run.app/
            clientId: clientID
            enabled: true
            secret: secret
            secretRefName: storageos-portal-client
            tenantId: tenantID
status: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: weave-policy-agent
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-policy-agent
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.5.3
  dependsOn:
  - name: ondat
  install:
    crds: CreateReplace
  interval: 1m0s
  upgrade:
    crds: CreateReplace
  values:
    policy-agent:
      caCertificate: ""
      certificate: ""
      config:
        accountId: ""
        admission:
          enabled: true
          sinks:
            k8sEventsSink:
              enabled: true
        audit:
          enabled: false
        clusterId: ""
      failurePolicy: Ignore
      key: ""
      persistence:
        enabled: false
      useCertManager: true
    policySource:
      enabled: false
status: {}
