apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: new-secret
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: test_secret_key
    creationPolicy: Owner
  data:
  - secretKey: new-secret
    remoteRef:
      key: "/dev/waleed"
      property: "test_secret_key"